baseURL = "http://repejota.com/"
languageCode = "en-us"
title = "Raül Pérez"
theme = "default"
sectionPagesMenu = "main"
copyright = "© 2018 - Raül Pérez"
isMultilingual = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home page"
    pre = "<i class='fas fa-home'></i>"
    url = "/"
    weight = -100

  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    title = "Articles"
    pre = "<i class='fas fa-rss'></i>"
    url = "/articles/"
    weight = 10

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    title = "Talks"
    pre = "<i class='far fa-comment-alt'></i>"
    url = "/talks/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    pre = "<i class='fas fa-folder'></i>"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About this site"
    pre = "<i class='fas fa-heart'></i>"
    url = "/about/"
    weight = 0
