name = "default"
license = "Apache 2"
licenselink = "https://github.com/repejota/repejota.github.io/blob/develop/LICENSE"
description = "Default themne for repejota.com."
homepage = "http://repejota.com"
tags = ["personal", "blog", "minimal", "simple", "clean"]
features = ["minimal", "responsive", "simple", "clean", "light"]
min_version = "0.30"

[author]
  name = "Raül Pérez"
  homepage = "http://repejota.com"
